return {
	"catppuccin/nvim",
	name = "catppuccin",
	enabled = false,
	priority = 1000,
	config = function()
		vim.cmd.colorscheme("catppuccin")
	end,
	opts = {
		flavour = "auto",
		integrations = {
			aerial = true,
			alpha = true,
			cmp = true,
			dashboard = true,
			flash = true,
			fzf = true,
			grug_far = true,
			gitsigns = true,
			headlines = true,
			illuminate = true,
			indent_blankline = { enabled = true },
			leap = true,
			lsp_trouble = true,
			mason = true,
			mini = true,
			navic = { enabled = true, custom_bg = "lualine" },
			neotest = true,
			neotree = true,
			noice = true,
			notify = true,
			snacks = true,
			telescope = true,
			treesitter_context = true,
			which_key = true,
		},
	},
}
