return {
	"ibhagwan/fzf-lua",
	dependencies = {"nvim-tree/nvim-web-devicons"},
	opts = {
		ui_select = true,
		file_icons = true,
		git_icons = true,
		multiprocess = true,
	},
	keys = {
		{"<leader>ff", "<cmd>FzfLua files<CR>", desc = "Find file"},
		{"<leader>fF", "<cmd>FzfLua global<CR>", desc = "Find anything"},
		{"<leader>fr", "<cmd>FzfLua resume<CR>", desc = "Find resume"},
		{"<leader>fg", "<cmd>FzfLua git_files<CR>", desc = "Find git file"},
		{"<leader>fc", "<cmd>FzfLua git_commits<CR>", desc = "Find git commit"},
		{"<leader>fb", "<cmd>FzfLua git_branches<CR>", desc = "Find git branch"},
		{"<leader>fs", "<cmd>FzfLua git_stash<CR>", desc = "Find git stash"},
		{"<leader>fb", "<cmd>FzfLua buffers<CR>", desc = "Find buffer"},
		{"<leader>fq", "<cmd>FzfLua quickfix<CR>", desc = "Find quickfix"},
		{"<leader>fG", "<cmd>FzfLua grep<CR>", desc = "Grep"},
		{"<leader>fl", "<cmd>FzfLua live_grep<CR>", desc = "Live grep"},
		{"<leader>fc", "<cmd>FzfLua complete_path<CR>", desc = "Complete path"},
		{"<leader>fe", "<cmd>FzfLua diagnostics_document<CR>", desc = "Diagnostics document"},
		{"<leader>fE", "<cmd>FzfLua diagnostics_workspace<CR>", desc = "Diagnostics workspace"},
		{"<leader>fC", "<cmd>FzfLua lsp_code_actions<CR>", desc = "Code actions"},
		{"<leader>ft", "<cmd>FzfLua lsp_definitions<CR>", desc = "LSP definitions"},
		{"<leader>fT", "<cmd>FzfLua lsp_declarations<CR>", desc = "LSP declarations"},
		{"<leader>fi", "<cmd>FzfLua lsp_implementations<CR>", desc = "LSP implementations"},
		{"<leader>fS", "<cmd>FzfLua lsp_document_symbols<CR>", desc = "LSP document symbols"},
		{"<leader>fm", "<cmd>FzfLua marks<CR>", desc = "Find mark"},
		{"<leader>fk", "<cmd>FzfLua keymaps<CR>", desc = "Find mark"},
		{"<leader>fP", "<cmd>FzfLua builtin<CR>", desc = "Global Find"},
		{"<leader>fp", "<cmd>FzfLua commands<CR>", desc = "Find command"},
	},
}
