# fix colors for nvim
set-option -sa terminal-overrides ",xterm*:Tc"

# enable mouse
set -g mouse on

# start win/pane numbering from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# rebind split to current path
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# prefix to ctrl+spc
#unbind C-b
#set -g prefix C-Space
#bind C-Space send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'erikw/powerline'
set -g @plugin 'erikw/tmux-dark-notify'

set -g @dark-notify-theme-path-light '~/.config/tmux/themes/modus_operandi.tmux'
set -g @dark-notify-theme-path-dark '~/.config/tmux/themes/modus_vivendi.tmux'

source $HOME/.config/tmux/themes/modus_vivendi.tmux

run '~/.config/tmux/plugins/tpm/tpm'

